Generate game map grid
TatuKalermo/bun-buddy pull request #10
Opened 2023-09-13 20:13 UTC by jessejp

Added utils directory with generateGrid function.

I set the mapWidth and map as stateful since the hot module replacement was bugging the JSX mapping otherwise.

2023-09-13 21:31 UTC, TatuKalermo requested changes
Maybe separate game grid from page.tsx to own component?

2023-09-14 08:28 UTC, jessejp commented
Yes! Added components/game directory

2023-09-14 09:12 UTC, TatuKalermo approved these changes

2023-09-14 09:13 UTC, TatuKalermo approved these changes

2023-09-14 09:13 UTC, merged